In [2]:
import torch

# torch Tensor

## torch.FloatTensor

In [3]:
a = torch.FloatTensor(2,3)
b = torch.FloatTensor([2,3,4,5])

print(a)
print(b)

tensor([[0.0000e+00, 0.0000e+00, 1.0257e-08],
        [8.1806e+20, 4.1022e-08, 6.6014e-07]])
tensor([2., 3., 4., 5.])


## torch.IntTensor

In [4]:
a = torch.IntTensor(2,3)
b = torch.IntTensor([2,3,4,5])

print(a)
print(b)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([2, 3, 4, 5], dtype=torch.int32)


## torch.rand

In [5]:
a = torch.rand(2,3)

print(a)

tensor([[0.5498, 0.9275, 0.0689],
        [0.5650, 0.8783, 0.5027]])


# torch.randn

In [6]:
a = torch.randn(2,3)

print(a)

tensor([[ 1.0752,  1.8518, -0.0601],
        [-0.5028, -0.6580, -1.1183]])


## torch.range

In [7]:
a = torch.range(1,20,1)

print(a)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])


ipykernel_launcher:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).


## torch.zeros

In [8]:
a = torch.zeros(2,3)

print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor的运算

## torch.abs

In [9]:
a = torch.randn(2,3)
print(a)

b = torch.abs(a)
print(b)

tensor([[ 0.1689, -1.0103, -0.6190],
        [ 0.5947,  0.1493,  1.0624]])
tensor([[0.1689, 1.0103, 0.6190],
        [0.5947, 0.1493, 1.0624]])


## torch.add

In [10]:
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.add(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.add(d,10)
print(e)

tensor([[-1.6054,  0.5996,  0.9086],
        [ 0.6338,  1.0899,  1.6870]])
tensor([[-1.1619,  1.2857, -0.6151],
        [-0.7924, -1.2299, -0.9688]])
tensor([[-2.7672,  1.8854,  0.2935],
        [-0.1586, -0.1400,  0.7181]])
tensor([[-1.6301, -0.6977,  0.8778],
        [-0.5618, -0.3694, -0.0928]])
tensor([[ 8.3699,  9.3023, 10.8778],
        [ 9.4382,  9.6306,  9.9072]])


## torch.clamp

In [11]:
a = torch.randn(2,3)
print(a)

b = torch.clamp(a,-0.1,0.1)
print(b)

tensor([[-0.4740, -1.4669, -1.2249],
        [-0.3287, -1.1627, -0.2838]])
tensor([[-0.1000, -0.1000, -0.1000],
        [-0.1000, -0.1000, -0.1000]])


## torch.div

In [12]:
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.div(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.div(d,10)
print(e)

tensor([[-0.3084, -2.0878, -0.6022],
        [ 0.8049,  0.4184, -0.6885]])
tensor([[-0.3069, -0.4352, -0.2613],
        [ 1.1396,  1.2544, -0.4434]])
tensor([[1.0050, 4.7976, 2.3050],
        [0.7063, 0.3335, 1.5529]])
tensor([[-0.0973, -0.2590, -1.2168],
        [-0.0583,  0.7523, -0.6660]])
tensor([[-0.0097, -0.0259, -0.1217],
        [-0.0058,  0.0752, -0.0666]])


## torch.mul

In [13]:
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.mul(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.mul(d,10)
print(e)

tensor([[ 0.1768,  0.2351,  0.0854],
        [ 1.2917,  0.3921, -1.7534]])
tensor([[ 0.9024,  0.1277, -0.6856],
        [ 0.8339,  0.7575, -0.0978]])
tensor([[ 0.1596,  0.0300, -0.0585],
        [ 1.0772,  0.2970,  0.1714]])
tensor([[ 0.7478, -0.0665,  0.9325],
        [ 0.5704,  0.6777, -1.5068]])
tensor([[  7.4782,  -0.6651,   9.3252],
        [  5.7036,   6.7765, -15.0676]])


## torch.pow

In [14]:
a = torch.randn(2,3)
print(a)

b = torch.pow(a,2)
print(b)

tensor([[ 0.1775, -0.4575,  0.6403],
        [-0.6465,  1.0521, -0.4622]])
tensor([[0.0315, 0.2093, 0.4100],
        [0.4179, 1.1069, 0.2137]])


## torch.mm

In [15]:
a = torch.randn(2,3)
print(a)

b = torch.randn(3,2)
print(b)

c = torch.mm(a,b)
print(c)

tensor([[-0.9990, -0.0987, -1.5422],
        [ 0.6133, -1.1323,  0.9440]])
tensor([[ 0.6603,  0.1177],
        [ 0.0956,  0.2087],
        [-0.4887,  0.9534]])
tensor([[ 0.0846, -1.6085],
        [-0.1646,  0.7359]])


## torch.mv

In [16]:
a = torch.randn(2,3)
print(a)

b = torch.randn(3)
print(b)

c = torch.mv(a,b)
print(c)

tensor([[-0.5721,  1.7955, -0.4462],
        [ 1.0276,  1.1134,  0.5679]])
tensor([-1.4634,  0.0176, -1.2115])
tensor([ 1.4094, -2.1722])
