In [1]:
import torch

# torch Tensor

## torch.FloatTensor

In [5]:
a = torch.FloatTensor(2,3)
b = torch.FloatTensor([2,3,4,5])

print(a)
print(b)

tensor([[9.2734e-14, 6.3058e-43, 1.4013e-45],
        [0.0000e+00, 1.7748e+28, 7.9316e+34]])
tensor([2., 3., 4., 5.])


## torch.IntTensor

In [6]:
a = torch.IntTensor(2,3)
b = torch.IntTensor([2,3,4,5])

print(a)
print(b)

tensor([[ 959459894,  945906488,  808661089],
        [ 929313072, 1664443186,  942880818]], dtype=torch.int32)
tensor([2, 3, 4, 5], dtype=torch.int32)


## torch.rand

In [7]:
a = torch.rand(2,3)

print(a)

tensor([[0.3128, 0.1639, 0.8257],
        [0.5355, 0.5358, 0.6266]])


# torch.randn

In [8]:
a = torch.randn(2,3)

print(a)

tensor([[ 0.0123, -1.3384,  1.5614],
        [ 0.2189,  1.4272,  3.0544]])


## torch.range

In [9]:
a = torch.range(1,20,1)

print(a)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])


D:\Anaconda3\envs\pytorch_env\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


## torch.zeros

In [10]:
a = torch.zeros(2,3)

print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor的运算

## torch.abs

In [12]:
a = torch.randn(2,3)
print(a)

b = torch.abs(a)
print(b)

tensor([[-0.9745,  0.9896,  1.0124],
        [ 1.3484, -0.6900,  0.0553]])
tensor([[0.9745, 0.9896, 1.0124],
        [1.3484, 0.6900, 0.0553]])


## torch.add

In [16]:
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.add(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.add(d,10)
print(e)

tensor([[-0.9284, -0.6011,  0.5022],
        [ 0.5029,  1.2899,  0.2576]])
tensor([[-0.3948,  0.6784, -0.0986],
        [ 1.8862,  0.2935, -1.1604]])
tensor([[-1.3232,  0.0773,  0.4036],
        [ 2.3891,  1.5834, -0.9028]])
tensor([[-1.8104, -1.0937, -1.0617],
        [ 1.6781,  0.0096,  0.8089]])
tensor([[ 8.1896,  8.9063,  8.9383],
        [11.6781, 10.0096, 10.8089]])


## torch.clamp

In [18]:
a = torch.randn(2,3)
print(a)

b = torch.clamp(a,-0.1,0.1)
print(b)

tensor([[ 0.7582,  0.6183, -0.2542],
        [ 0.5340, -0.0977,  0.6001]])
tensor([[ 0.1000,  0.1000, -0.1000],
        [ 0.1000, -0.0977,  0.1000]])


## torch.div

In [19]:
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.div(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.div(d,10)
print(e)

tensor([[-0.9974, -1.3681,  1.2700],
        [-0.0625,  0.6561,  0.4479]])
tensor([[-0.6062,  0.1325, -0.5771],
        [ 1.2832,  0.3913,  0.0404]])
tensor([[  1.6452, -10.3243,  -2.2008],
        [ -0.0487,   1.6768,  11.0870]])
tensor([[-0.1177, -0.9731,  1.9104],
        [ 1.5920, -1.0234, -0.2268]])
tensor([[-0.0118, -0.0973,  0.1910],
        [ 0.1592, -0.1023, -0.0227]])


## torch.mul

In [20]:
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.mul(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.mul(d,10)
print(e)

tensor([[ 0.0389, -0.3661, -0.2866],
        [-1.4218, -1.5303,  1.3115]])
tensor([[ 0.1865, -1.0984, -0.3576],
        [ 0.2900,  0.5965, -1.1360]])
tensor([[ 0.0073,  0.4021,  0.1025],
        [-0.4123, -0.9129, -1.4898]])
tensor([[-0.2174, -1.1605,  0.7236],
        [ 1.3425,  1.3135,  1.5572]])
tensor([[ -2.1740, -11.6047,   7.2358],
        [ 13.4252,  13.1346,  15.5722]])


## torch.pow

In [22]:
a = torch.randn(2,3)
print(a)

b = torch.pow(a,2)
print(b)

tensor([[-1.7624,  0.0689,  2.4755],
        [-1.1925,  0.5063,  1.5483]])
tensor([[3.1061e+00, 4.7493e-03, 6.1280e+00],
        [1.4220e+00, 2.5635e-01, 2.3973e+00]])


## torch.mm

In [23]:
a = torch.randn(2,3)
print(a)

b = torch.randn(3,2)
print(b)

c = torch.mm(a,b)
print(c)

tensor([[ 1.0444,  1.0644, -2.0657],
        [ 1.6060,  0.7419,  0.3797]])
tensor([[-1.1342, -0.9102],
        [-1.0353,  0.2347],
        [ 1.1194,  1.2468]])
tensor([[-4.5989, -3.2763],
        [-2.1647, -0.8143]])


## torch.mv

In [25]:
a = torch.randn(2,3)
print(a)

b = torch.randn(3)
print(b)

c = torch.mv(a,b)
print(c)

tensor([[-0.9950, -1.2932, -0.5685],
        [ 0.4991,  2.4139, -0.0962]])
tensor([1.1706, 0.2817, 0.4686])
tensor([-1.7955,  1.2192])
